name: pi3-36
channels:
  - conda-forge
  - defaults
  - labscript-suite
dependencies:
  - python=3.6
  - numpy<=1.26
  - scipy
  - ipython
  - pydaqmx
  - pip
  - pip:
      - pyqt5
      - traitsui
      - chaco
      - nidaqmx
      - pyvisa