name: pi3
channels:
  - conda-forge
  - defaults
  - labscript-suite
dependencies:
  - python=3.11
  - numpy=1.26
  - scipy
  - ipython
  - pydaqmx
  - pip
  - pip:
      - pyqt5
      - traitsui==8.0.0
      - chaco
      - nidaqmx
      - pyvisa
      - pulsestreamer