name: pi3
channels:
  - conda-forge
  - defaults
  - labscript-suite
dependencies:
  - python=3.11
  - numpy=1.26
  - scipy
  - ipython
  - pydaqmx
  - pip
  - pip:
      - matplotlib
      - pyqt5
      - traitsui==8.0.0
      - chaco
      - nidaqmx
      - pyvisa
      - pulsestreamer
variables:
  timetagger_install_path: "C:\Program Files\Swabian Instruments\Time Tagger"
  pythonpath: "C:\Program Files\Swabian Instruments\Time Tagger\driver\python"
